apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: connaisseur
spec:
  namespace: connaisseur
  chart:
    name: connaisseur
    version: 0.2.0
    repository:
      name: example
      url: file:///charts/example
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    alerting:
      cluster: api-zkaiser-fpga-psap-aws-rhperfscale-org:6443
    rootPubKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWwJ+uJydgt5HMlMFfoWlX3PFlZJJ
      oVbbosniAAphIOt37/5qYTUtUsal1IIAk0Nx+qcAKlOzBWe96RGr001QtQ==
      -----END PUBLIC KEY-----
    isCosign: true



