apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T11:51:45.376000631Z"
    description: Simple go app to showcase cert-manager intergration
    digest: 810392826cd90e1ac0cecdde50608ccc68b1db684eb1efc44bae13be4f4d2625
    icon: https://avatars.githubusercontent.com/u/55542927
    name: cert-manager
    type: application
    urls:
    - file:///charts/olm/cert-manager-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-23T11:51:45.375704415Z"
