apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2021-06-23T14:22:55.590464204Z"
    description: Simple go app to showcase cert-manager intergration
    digest: e24ddb5a66d9b3f5ce13573b3f6e2c08b17a76c380f848342376e59c0bc682a6
    icon: https://avatars.githubusercontent.com/u/55542927
    name: cert-manager
    type: application
    urls:
    - file:///charts/experimental/cert-manager-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2021-06-23T14:22:55.583172475Z"
    description: Simple go app to showcase cert-manager intergration
    digest: 93b710caea95703cfe78080d5b9ae53566768b27b7b7e881986c2cfb78ec905d
    icon: https://avatars.githubusercontent.com/u/55542927
    name: cert-manager
    type: application
    urls:
    - file:///charts/experimental/cert-manager-1.3.0.tgz
    version: 1.3.0
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-23T14:22:55.590684509Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 29e2cc094e16d6cf239d3e01fa9e8df0ca33267841ed55ed8f9a5b9b7eba0d4e
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/experimental/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-23T14:22:55.573419942Z"
