apiVersion: v1
entries:
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-15T09:30:23.82280676Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 1f572211dec64abbbcfb6fc76ee88f12d49163056b8c2a7266313a85a26ede44
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/experimental/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-15T09:30:23.822516874Z"
