apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: driver-toolkit
spec:
  namespace: driver-toolkit
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/openshift-psap/kmods-via-containers"
