apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: special-resource-preamble
spec:
  chart:
    name: preamble
    repository:
      name: example
      url: file:///charts/example/
    version: 0.0.1
  namespace: preamble
  nodeSelector:
    node-role.kubernetes.io/worker: ""
