apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: cert-manager
spec:
  namespace: cert-manager
  chart:
    name: cert-manager
    version: 0.0.1
    repository:
      name: example
      url: file:///charts/olm
