apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - 0000_namespace.yaml 
  - 0001_operatorgroup.yaml
  - 0002_subscription.yaml
  - 0003_cr.yaml 
  name: ping-pong
namespace: ping-pong
