apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: fpga-xrt-driver
spec:
  chart:
    name: fpga-xrt-driver
    repository: file:///charts/xilinx
    version: 0.1.0
  namespace: fpga-xrt-driver
  nodeSelector:
    feature.node.kubernetes.io/pci-1d0f.present: "true"
    node.kubernetes.io/instance-type: f1.2xlarge

  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1


  driverContainer:
    source:
      git:
        ref: "main"
        uri: "https://github.com/openshift-psap/kvc-xilinx-xrt.git"

  dependencies:
  - name: driver-container-base
    version: "0.1.0"
    repository: "file:///charts/example"
    tags:
    - image-puller
