apiVersion: v1
entries:
  fpga-xrt-driver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-05-19T12:12:32.752513258Z"
    description: A Helm chart for Kubernetes
    digest: a155475b27f694a32885df58bbc1f916bd3124c152f656edb68abc16ccbc4be1
    name: fpga-xrt-driver
    type: application
    urls:
    - file:///charts/xilinx/fpga-xrt-driver-0.1.0.tgz
    version: 0.1.0
generated: "2021-05-19T12:12:32.752183241Z"
