apiVersion: v1
entries:
  fpga-xrt-driver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-05-20T11:08:15.499663496Z"
    description: A Helm chart for Kubernetes
    digest: b56042b5d2a6e81127d064a1614fe9a1cedcb42d348d1e30288ff419bc7c2d0c
    name: fpga-xrt-driver
    type: application
    urls:
    - file:///charts/xilinx/fpga-xrt-driver-4.7.11.tgz
    version: 4.7.11
generated: "2021-05-20T11:08:15.499328679Z"
