apiVersion: v1
entries:
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-16T09:59:31.122531609Z"
    description: Simple go app to showcase cert-manager intergration
    digest: 71bdadb211b18a4009b7fa925aa8a4f62aa540f4aba66ce34f54d934bbb2ec73
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-16T09:59:31.122712603Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 111165bc2ec492896ef74e92de0b63009cb9af6ba5973e8341bdf1fbb069f0ff
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-16T09:59:31.122161941Z"
