apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-05-19T12:12:32.525753369Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: cc08d01bbc92169c0c3cd29811a5ae8a34486b73316ac3ef109bc4895622ce7b
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/example/driver-container-base-0.1.0.tgz
    version: 0.1.0
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-05-19T12:12:32.525952624Z"
    description: Simple go app to showcase cert-manager intergration
    digest: 78dc0b7e9a05c04b6381db5621ae6b5197631dfc5bfa764ea012d51e5fc8cd99
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-05-19T12:12:32.526137168Z"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 2e3d39ee62e041fefe2b6541c788aa2406fe5c4cb0cc93c68eadaeacfc6fa35a
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-05-19T12:12:32.525395972Z"
