apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-16T09:59:31.043159853Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: d42e24aef41c965f7e2b52af97cdf57e4c0dfbb8c855ac7fb3e41155f7b63291
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-16T09:59:31.042801445Z"
