apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-25T08:29:01.361938192Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 9d39c11e85d8bd1ddb2b93bce34c64b7eb434cd1ce37a7a924d9c6592add765a
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-25T08:29:01.361609594Z"
