apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-24T16:39:42.933805145Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: cbb485d18e7acd92e20d7e751b003ff6a00431e2063a2494b73ca40bb392c1b1
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-24T16:39:42.933462148Z"
