apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.specialresource.metadata.name }}
  namespace: {{ .Values.specialresource.metadata.name }}
spec:
  channel: stable
  name: cert-manager-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace