apiVersion: v1
entries:
  shipwright:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2021-07-08T11:40:40.482965122Z"
    description: Build v2
    digest: f197a2ef558e1ff3713f6194b32e11f58ca6edd8bd1de9853681c7734fce0a40
    icon: https://avatars.githubusercontent.com/u/55542927
    name: shipwright
    type: application
    urls:
    - file:///charts/staging/shipwright-4.7.0.tgz
    version: 4.7.0
generated: "2021-07-08T11:40:40.48197582Z"
