apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: cert-manager
spec:
  namespace: cert-manager
  chart:
    name: cert-manager
    version: 1.4.0
    repository:
      name: experimental
      url: file:///charts/experimental
