name: verify

on: push

jobs: 
  go-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"

    - name: make lint
      run: make lint

