name: image

on:
  pull_request_target:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    if: contains(github.event_name, 'workflow_dispatch') ||
        contains(github.event.pull_request.head.repo.full_name, 'openshift-psap/special-resource-operator')
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 10
    - run: sudo apt-get install fuse-overlayfs
    - run: TAG=pr-${{ steps.short-sha.outputs.sha }} make local-image-build
    - uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD}}
    - run: TAG=pr-${{ steps.short-sha.outputs.sha }} make local-image-push
