name: kube-lint

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  lint:
    name: kube-linter
    runs-on: ubuntu-latest
    if: (github.event_name == 'labeled' && contains(toJSON(github.event.pull_request.labels), '"ok-to-test",')) ||
        (github.event.pull_request.head.repo.full_name == 'openshift-psap/special-resource-operator')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make kube-lint

