name: kube-lint

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  lint:
    name: kube-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make kube-lint

