name: openshift

on:
  workflow_run:
    workflows: ["image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  openshift:
    name: test-e2e
    runs-on: ubuntu-latest
    if: (github.event.action == 'labeled' && github.event.label.name == 'ok-to-test') ||
        (github.event.pull_request.head.repo.full_name == 'openshift-psap/special-resource-operator')
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 10
    - uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_username: ${{ secrets.OPENSHIFT_USERNAME }}
        openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
        insecure_skip_tls_verify: true
        namespace: default
    - run: make undeploy
    - run: TAG=pr-${{ steps.short-sha.outputs.sha }} make go-deploy-manifests
    - run: make test-e2e
    - run: make go-undeploy-manifests
