name: OpenShift - Tests

env:
  REGISTRY: quay.io/openshift-psap
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

on: push

jobs: 
  openshift-ci-cd:
    name: Build and Deploy to OpenShift
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"

    - name: make verify 
      run: make verify

    - name: make unit
      run: make unit

    - name: make lint
      run: make lint

    - name: make local-image-build 
      run: make local-image-build
    
    - name: auth.json
      run: |
        [ -d ~/.docker ] || mkdir ~/.docker
        cat > ~/.docker/config.json <<'EOF'
        ${{ secrets.AUTH_JSON }}
        EOF
    
    - name: make local-image-push
      run: make local-image-push
    
    - name: oc login 
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: default

    - name: make undeploy
      run: make undeploy

    - name: make test-e2e
      run: make test-e2e
  
