name: openshift

env:
  REGISTRY: quay.io/openshift-psap
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

on: 
  repository_dispatch:
    types: [image-build]

jobs: 
  openshift:
    name: test-e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"
    
    - name: oc login 
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: default

    - name: make test-e2e
      run: make test-e2e
  
