name: remove-label

on:
  pull_request_target:
    types: [synchronize]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  remove:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != 'openshift-psap/special-resource-operator'
    steps:
    - name: removelabel
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        label: ok-to-test
        type: remove
