name: run-tests

on:
  pull_request_target:
    types: [synchronize, labeled]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  remove-label:
    runs-on: ubuntu-latest
    if: contains(github.event.action, 'synchronize')
    steps:
    - name: removelabel
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        label: ok-to-test
        type: remove
  run:	
    name: run	
    runs-on: ubuntu-20.04	
    if: contains(github.event.action, 'labeled') && contains(github.event.label.name, 'ok-to-test') && ! contains(github.event.pull_request.head.repo.full_name, 'openshift-psap/special-resource-operator')	
    steps:	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: go-lint	
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: kube-lint	
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: image	
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: unit
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: verify
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
    - name: Invoke workflow without inputs	
      uses: benc-uk/workflow-dispatch@v1	
      with:	
        workflow: openshift
        token: ${{ secrets.REPO_ACCESS_TOKEN }}	
