name: unlabel

on:
  pull_request_target:
    types: [synchronize, labeled]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    if: contains(github.event.action, 'synchronize')
    steps:
    - name: removelabel
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        label: ok-to-test
        type: remove
  
