name: test

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  context:
    name: context
    runs-on: ubuntu-20.04
    if: contains(toJSON(github.event.pull_request.labels), '"ok-to-test",')
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "github context:\n $GITHUB_CONTEXT"
