name: test

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  context:
    name: context
    runs-on: ubuntu-20.04
    if: contains('ok-to-test', 'ok-to-test')
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump GitHub Labels
      env:
        GITHUB_LABELS: ${{ github.event.pull_request.labels.*.name }}
      run: echo "$GITHUB_LABELS"
