name: test-target

on:
  pull_request_target:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  ok-to-test:
    name: ok-to-test
    runs-on: ubuntu-20.04
    if: contains(toJSON(github.event.pull_request.labels), '"ok-to-test",')
    steps:
    - name: hello
      run: echo "Hello World"
  repo-test:
    name: main-repo
    runs-on: ubuntu-20.04
    if: contains(github.repository, 'openshift-psap/special-resource-operator')
    steps:
    - name: hello
      run: echo "Hello World"

