name: unit

on: 
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs: 
  unit:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make unit

