name: verify

on: 
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs: 
  verify:
    name: fmt-vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make verify

